kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: init-script
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Mi
