kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
